uceap_logging.settings:
  type: config_object
  label: 'UCEAP Logging Settings'
  mapping:
    sensitive_fields:
      type: sequence
      label: 'Sensitive fields'
      sequence:
        type: string
        label: 'Field name'
